name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: make
      
    - name: Build prod
      run: make prod
    
    - name: deploy
      run: ./deploy.sh
    
    - name: Push to gh-pages
      uses: actions-js/push@gh-pages
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages